-- Catálogo de Patologías: 129 generales + detalle CIE, TODO en MAYÚSCULAS y deduplicado.
-- IDEMPOTENTE: re-ejecutable (ON CONFLICT por nombre). Supera a seed_patologias.sql (Título, obsoleto).

-- Normaliza nombres existentes: quita comas.
UPDATE "Patologia" SET "nombre" = TRIM(REGEXP_REPLACE("nombre", '\s*,\s*', ' ', 'g')) WHERE "nombre" LIKE '%,%';

INSERT INTO "Patologia" ("id", "nombre") VALUES
  (gen_random_uuid(), 'ABDOMEN AGUDO'),
  (gen_random_uuid(), 'ABORTOS ESPONTÁNEOS'),
  (gen_random_uuid(), 'ACNÉ'),
  (gen_random_uuid(), 'ACV ISQUÉMICO'),
  (gen_random_uuid(), 'ADENOMEGALIA'),
  (gen_random_uuid(), 'ALOPECIA'),
  (gen_random_uuid(), 'ALERGIA RESPIRATORIA'),
  (gen_random_uuid(), 'AMIGDALITIS'),
  (gen_random_uuid(), 'AMENORREA'),
  (gen_random_uuid(), 'AMENORREA PRIMARIA'),
  (gen_random_uuid(), 'AMENORREA SECUNDARIA'),
  (gen_random_uuid(), 'ANAOVULACIÓN'),
  (gen_random_uuid(), 'ANEMIA'),
  (gen_random_uuid(), 'ANEURISMA'),
  (gen_random_uuid(), 'ANGINA'),
  (gen_random_uuid(), 'ANGOR'),
  (gen_random_uuid(), 'ANOREXIA'),
  (gen_random_uuid(), 'APENDICITIS'),
  (gen_random_uuid(), 'ARRITMIA'),
  (gen_random_uuid(), 'ARRITMIAS'),
  (gen_random_uuid(), 'ARTRALGIA'),
  (gen_random_uuid(), 'ARTRITIS REUMATOIDEA'),
  (gen_random_uuid(), 'ARTROSIS'),
  (gen_random_uuid(), 'ASMA'),
  (gen_random_uuid(), 'ASTENIA'),
  (gen_random_uuid(), 'BAJO PESO'),
  (gen_random_uuid(), 'BOCIO'),
  (gen_random_uuid(), 'BRONQUITIS OBSTRUCTIVA'),
  (gen_random_uuid(), 'CEFALEA'),
  (gen_random_uuid(), 'CIRROSIS'),
  (gen_random_uuid(), 'CLIMATERIO'),
  (gen_random_uuid(), 'COLELITIASIS'),
  (gen_random_uuid(), 'CÓLICO RENAL'),
  (gen_random_uuid(), 'CONJUNTIVITIS'),
  (gen_random_uuid(), 'CONSTIPACIÓN'),
  (gen_random_uuid(), 'CONTROL BY PASS'),
  (gen_random_uuid(), 'CONTROL DE CA.'),
  (gen_random_uuid(), 'DERMATITIS'),
  (gen_random_uuid(), 'DESNUTRICIÓN'),
  (gen_random_uuid(), 'DIABETES MELLITUS'),
  (gen_random_uuid(), 'DIARREA'),
  (gen_random_uuid(), 'DISLIPEMIA'),
  (gen_random_uuid(), 'DISNEA'),
  (gen_random_uuid(), 'DISPEPSIA'),
  (gen_random_uuid(), 'DISURIA'),
  (gen_random_uuid(), 'DOLOR ABDOMINAL'),
  (gen_random_uuid(), 'ECLAMPSIA'),
  (gen_random_uuid(), 'EDEMAS'),
  (gen_random_uuid(), 'EMBARAZO - CONTROL 1ER. TRIMESTRE'),
  (gen_random_uuid(), 'EMBARAZO - CONTROL 2DO. TRIMESTRE'),
  (gen_random_uuid(), 'EMBARAZO - CONTROL 3ER. TRIMESTRE'),
  (gen_random_uuid(), 'ENFERMEDAD DE HODGKIN'),
  (gen_random_uuid(), 'ENFERMEDAD DE TRANSMISIÓN SEXUAL'),
  (gen_random_uuid(), 'EPISTAXIS'),
  (gen_random_uuid(), 'EPILEPSIA'),
  (gen_random_uuid(), 'EPOC - INSUFICIENCIA RESPIRATORIA'),
  (gen_random_uuid(), 'ESCABIOSIS'),
  (gen_random_uuid(), 'ETILISMO'),
  (gen_random_uuid(), 'FARINGITIS'),
  (gen_random_uuid(), 'FIBROSIS QUÍSTICA'),
  (gen_random_uuid(), 'FIEBRE'),
  (gen_random_uuid(), 'FIEBRE REUMÁTICA'),
  (gen_random_uuid(), 'GASTROENTERITIS'),
  (gen_random_uuid(), 'GOTA'),
  (gen_random_uuid(), 'HEMATOMAS'),
  (gen_random_uuid(), 'HEMATURIA'),
  (gen_random_uuid(), 'HEPATITIS'),
  (gen_random_uuid(), 'HEPATOMEGALIA'),
  (gen_random_uuid(), 'HEPATOPATÍA'),
  (gen_random_uuid(), 'HERPES'),
  (gen_random_uuid(), 'HIPERCOLESTEROLEMIA / COLESTEROLEMIA'),
  (gen_random_uuid(), 'HIPERTENSIÓN ARTERIAL'),
  (gen_random_uuid(), 'HIPERTIROIDISMO'),
  (gen_random_uuid(), 'HIPOGONADISMO MASCULINO'),
  (gen_random_uuid(), 'HIPOTIROIDISMO'),
  (gen_random_uuid(), 'HIRSUTISMO'),
  (gen_random_uuid(), 'ICTERICIA'),
  (gen_random_uuid(), 'INFECCIÓN URINARIA'),
  (gen_random_uuid(), 'INFERTILIDAD FEMENINA'),
  (gen_random_uuid(), 'INFERTILIDAD MASCULINA'),
  (gen_random_uuid(), 'INSUFICIENCIA CARDÍACA'),
  (gen_random_uuid(), 'INSUFICIENCIA RENAL CRÓNICA/AGUDA'),
  (gen_random_uuid(), 'INTOXICACIÓN'),
  (gen_random_uuid(), 'LEUCEMIA'),
  (gen_random_uuid(), 'LINFOMA'),
  (gen_random_uuid(), 'LINFOMA NO-HODGKIN'),
  (gen_random_uuid(), 'LIPOTIMIA'),
  (gen_random_uuid(), 'LITIASIS VESICULAR'),
  (gen_random_uuid(), 'LUMBALGIA'),
  (gen_random_uuid(), 'LUPUS ERITEMATOSO'),
  (gen_random_uuid(), 'MAREOS'),
  (gen_random_uuid(), 'MELANOMA'),
  (gen_random_uuid(), 'MENOPAUSIA'),
  (gen_random_uuid(), 'METRORRAGIA'),
  (gen_random_uuid(), 'METABOLOPATÍA'),
  (gen_random_uuid(), 'MIALGIA'),
  (gen_random_uuid(), 'MIELOMA'),
  (gen_random_uuid(), 'MONONUCLEOSIS Y LA INFECCIOSA'),
  (gen_random_uuid(), 'MEGACOLON'),
  (gen_random_uuid(), 'NEUMOPATÍA'),
  (gen_random_uuid(), 'OBESIDAD'),
  (gen_random_uuid(), 'OSTEOPENIA'),
  (gen_random_uuid(), 'OSTEOPOROSIS'),
  (gen_random_uuid(), 'PAROTIDITIS'),
  (gen_random_uuid(), 'PIELONEFRITIS'),
  (gen_random_uuid(), 'POLIARTRALGIAS'),
  (gen_random_uuid(), 'POLIDIPSIA'),
  (gen_random_uuid(), 'PRECORDIALGIA - DOLOR PRECORDIAL'),
  (gen_random_uuid(), 'PREQUIRÚRGICO'),
  (gen_random_uuid(), 'PROSTATISMO'),
  (gen_random_uuid(), 'PRURITO'),
  (gen_random_uuid(), 'PSORIASIS'),
  (gen_random_uuid(), 'RAYNAUD ENFERMEDAD - SÍNDROME'),
  (gen_random_uuid(), 'REACCIÓN ALÉRGICA'),
  (gen_random_uuid(), 'RINITIS'),
  (gen_random_uuid(), 'RINOFARINGITIS AGUDA'),
  (gen_random_uuid(), 'SARCOMA'),
  (gen_random_uuid(), 'SÍNDROME DE LA SILLA TURCA'),
  (gen_random_uuid(), 'SÍNDROME DE OVARIO POLIQUÍSTICO (SOPQ)'),
  (gen_random_uuid(), 'SÍNDROME FEBRIL PROLONGADO'),
  (gen_random_uuid(), 'SÍNDROME VERTIGINOSO'),
  (gen_random_uuid(), 'SINUSITIS'),
  (gen_random_uuid(), 'SOBREPESO'),
  (gen_random_uuid(), 'SUDORACIÓN'),
  (gen_random_uuid(), 'TOS CRÓNICA'),
  (gen_random_uuid(), 'ÚLCERA GÁSTRICA / DUODENAL'),
  (gen_random_uuid(), 'URTICARIA'),
  (gen_random_uuid(), 'VÓMITOS'),
  (gen_random_uuid(), 'OTROS'),
  (gen_random_uuid(), 'ANEMIA SIN ESPECIFICAR'),
  (gen_random_uuid(), 'ANEMIA REFRACTARIA SIN SIDEROBLASTOS ASI DESCRITA'),
  (gen_random_uuid(), 'ANEMIA POR DEFICIENCIA DE VITAMINA B12'),
  (gen_random_uuid(), 'ANEMIA POR DEFICIENCIA DE FOLATOS'),
  (gen_random_uuid(), 'OTRAS ANEMIAS NUTRICIONALES'),
  (gen_random_uuid(), 'ANEMIA DEBIDA A TRASTORNOS ENZIMATICOS'),
  (gen_random_uuid(), 'ANEMIA FALCIFORME CON CRISIS'),
  (gen_random_uuid(), 'OTRAS ANEMIAS HEMOLITICAS HEREDITARIAS'),
  (gen_random_uuid(), 'ANEMIA HEMOLITICA ADQUIRIDA'),
  (gen_random_uuid(), 'OTRAS ANEMIAS APLASTICAS'),
  (gen_random_uuid(), 'ANEMIA POSTHEMORRAGICA AGUDA'),
  (gen_random_uuid(), 'ANEMIA EN ENFERMEDADES CRONICAS CLASIFICADAS EN OTRA PARTE'),
  (gen_random_uuid(), 'OTRAS ANEMIAS'),
  (gen_random_uuid(), 'ANEMIA QUE COMPLICA EL EMBARAZO EL PARTO Y EL PUERPERIO'),
  (gen_random_uuid(), 'ANEURISMA CARDIACO'),
  (gen_random_uuid(), 'ANEURISMA DE LA ARTERIA PULMONAR'),
  (gen_random_uuid(), 'ANEURISMA CEREBRAL SIN RUPTURA'),
  (gen_random_uuid(), 'ANEURISMA Y DISECCION AORTICOS'),
  (gen_random_uuid(), 'OTROS ANEURISMAS'),
  (gen_random_uuid(), 'ARRITMIAS SIN ESPECIFICAR'),
  (gen_random_uuid(), 'OTRAS ARRITMIAS CARDIACAS'),
  (gen_random_uuid(), 'OTRAS ARRITMIAS CARDIACAS ESPECIFICADAS'),
  (gen_random_uuid(), 'OTRAS ARTRITIS REUMATOIDEAS SEROPOSITIVAS'),
  (gen_random_uuid(), 'ARTRITIS REUMATOIDEA SEROPOSITIVA SIN OTRA ESPECIFICACION'),
  (gen_random_uuid(), 'ARTROSIS SIN ESPECIFICAR'),
  (gen_random_uuid(), 'HIDRARTROSIS INTERMITENTE'),
  (gen_random_uuid(), 'POLIARTROSIS'),
  (gen_random_uuid(), 'OTRAS POLIARTROSIS'),
  (gen_random_uuid(), 'COXARTROSIS [ARTROSIS DE LA CADERA]'),
  (gen_random_uuid(), 'GONARTROSIS [ARTROSIS DE LA RODILLA]'),
  (gen_random_uuid(), 'GONARTROSIS NO ESPECIFICADA'),
  (gen_random_uuid(), 'ARTROSIS DE LA PRIMERA ARTICULACION CARPOMETACARPIANA'),
  (gen_random_uuid(), 'OTRAS ARTROSIS'),
  (gen_random_uuid(), 'HEMARTROSIS SIN ESPECIFICAR'),
  (gen_random_uuid(), 'FALTA DE CONSOLIDACION DE FRACTURA [SEUDOARTROSIS]'),
  (gen_random_uuid(), 'SEUDOARTROSIS CONSECUTIVA A FUSION O ARTRODESIS'),
  (gen_random_uuid(), 'ASTENIA SIN ESPECIFICAR'),
  (gen_random_uuid(), 'SINDROME DE FATIGA POSTVIRAL'),
  (gen_random_uuid(), 'FRACTURA DE VERTEBRA POR FATIGA'),
  (gen_random_uuid(), 'MALESTAR Y FATIGA'),
  (gen_random_uuid(), 'FATIGA POR CALOR TRANSITORIA'),
  (gen_random_uuid(), 'DIABETES MELLITUS SIN ESPECIFICAR'),
  (gen_random_uuid(), 'DIABETES MELLITUS INSULINODEPENDIENTE'),
  (gen_random_uuid(), 'DIABETES MELLITUS INSULINODEPENDIENTE CON COMPLICACIONES MULTIPLES'),
  (gen_random_uuid(), 'DIABETES MELLITUS INSULINODEPENDIENTE CON COMPLICACIONES NO ESPECIFICADAS'),
  (gen_random_uuid(), 'DIABETES MELLITUS NO INSULINODEPENDIENTE'),
  (gen_random_uuid(), 'DIABETES MELLITUS NO INSULINODEPENDIENTE CON COMPLICACIONES MULTIPLES'),
  (gen_random_uuid(), 'DIABETES MELLITUS NO INSULINODEPENDIENTE CON COMPLICACIONES NO ESPECIFICAD'),
  (gen_random_uuid(), 'DIABETES MELLITUS ASOCIADA CON DESNUTRICION'),
  (gen_random_uuid(), 'OTRAS DIABETES MELLITUS ESPECIFICADAS'),
  (gen_random_uuid(), 'DIABETES MELLITUS NO ESPECIFICADA'),
  (gen_random_uuid(), 'DIABETES INSIPIDA'),
  (gen_random_uuid(), 'DIABETES MELLITUS PREEXISTENTE INSULINODEPENDIENTE EN EL EMBARAZO'),
  (gen_random_uuid(), 'DIABETES MELLITUS PREEXISTENTE NO INSULINODEPENDIENTE EN EL EMBARAZO'),
  (gen_random_uuid(), 'SINDROME DEL RECIEN NACIDO DE MADRE CON DIABETES GESTACIONAL'),
  (gen_random_uuid(), 'EXAMEN DE PESQUISA ESPECIAL PARA DIABETES MELLITUS'),
  (gen_random_uuid(), 'HISTORIA FAMILIAR DE DIABETES MELLITUS'),
  (gen_random_uuid(), 'DIARREA Y GASTROENTERITIS DE PRESUNTO ORIGEN INFECCIOSO'),
  (gen_random_uuid(), 'SINDROME DEL COLON IRRITABLE CON DIARREA'),
  (gen_random_uuid(), 'DIARREA FUNCIONAL'),
  (gen_random_uuid(), 'DIARREA NEONATAL NO INFECCIOSA'),
  (gen_random_uuid(), 'ENFERMEDAD POR VIH RESULTANTE EN OTROS TIPOS DE LINFOMA NO HODGKIN'),
  (gen_random_uuid(), 'OTROS TIPOS DE ENFERMEDAD DE HODGKIN'),
  (gen_random_uuid(), 'ENFERMEDAD DE HODGKIN NO ESPECIFICADA'),
  (gen_random_uuid(), 'LINFOMA NO HODGKIN FOLICULAR [NODULAR]'),
  (gen_random_uuid(), 'LINFOMA NO HODGKIN DIFUSO'),
  (gen_random_uuid(), 'LINFOMA NO HODGKIN DE OTRO TIPO Y EL NO ESPECIFICADO'),
  (gen_random_uuid(), 'FARINGITIS GONOCOCICA'),
  (gen_random_uuid(), 'FARINGITIS VESICULAR ENTEROVIRICA'),
  (gen_random_uuid(), 'RINOFARINGITIS AGUDA [RESFRIADO COMUN]'),
  (gen_random_uuid(), 'FARINGITIS AGUDA'),
  (gen_random_uuid(), 'FARINGITIS ESTREPTOCOCICA'),
  (gen_random_uuid(), 'LARINGOFARINGITIS AGUDA'),
  (gen_random_uuid(), 'RINITIS RINOFARINGITIS Y FARINGITIS CRONICAS'),
  (gen_random_uuid(), 'FARINGITIS CRONICA'),
  (gen_random_uuid(), 'FIBROSIS QUISTICA'),
  (gen_random_uuid(), 'FIBROSIS QUISTICA CON MANIFESTACIONES PULMONARES'),
  (gen_random_uuid(), 'FIBROSIS QUISTICA CON MANIFESTACIONES INTESTINALES'),
  (gen_random_uuid(), 'FIEBRES RECURRENTES'),
  (gen_random_uuid(), 'FIEBRE Q'),
  (gen_random_uuid(), 'FIEBRE DE ORIGEN DESCONOCIDO'),
  (gen_random_uuid(), 'FIEBRE CON ESCALOFRIO'),
  (gen_random_uuid(), 'FIEBRE PERSISTENTE'),
  (gen_random_uuid(), 'FIEBRES TIFOIDEA Y PARATIFOIDEA'),
  (gen_random_uuid(), 'OTRAS FIEBRES VIRALES TRANSMITIDAS POR ARTROPODOS NO CLASIFICADAS EN OTRA'),
  (gen_random_uuid(), 'FIEBRE AMARILLA'),
  (gen_random_uuid(), 'FIEBRE HEMORRAGICA DE JUNIN'),
  (gen_random_uuid(), 'FIEBRE REUMATICA SIN MENCION DE COMPLICACION CARDIACA'),
  (gen_random_uuid(), 'FIEBRE REUMATICA CON COMPLICACION CARDIACA'),
  (gen_random_uuid(), 'ERITEMA MARGINADO EN LA FIEBRE REUMATICA AGUDA (I00+)'),
  (gen_random_uuid(), 'OTRAS COLITIS Y GASTROENTERITIS NO INFECCIOSAS'),
  (gen_random_uuid(), 'COLITIS Y GASTROENTERITIS DEBIDAS A RADIACION'),
  (gen_random_uuid(), 'COLITIS Y GASTROENTERITIS TOXICAS'),
  (gen_random_uuid(), 'COLITIS Y GASTROENTERITIS ALERGICAS Y DIETETICAS'),
  (gen_random_uuid(), 'COLITIS Y GASTROENTERITIS NO INFECCIOSAS NO ESPECIFICADAS'),
  (gen_random_uuid(), 'ENFERMEDAD DE CROHN [ENTERITIS REGIONAL]'),
  (gen_random_uuid(), 'OTRAS ENTERITIS VIRALES'),
  (gen_random_uuid(), 'HEMATURIA NO ESPECIFICADA'),
  (gen_random_uuid(), 'HEMATURIA RECURRENTE Y PERSISTENTE'),
  (gen_random_uuid(), 'HEPATITIS AGUDA TIPO A'),
  (gen_random_uuid(), 'HEPATITIS AGUDA TIPO B'),
  (gen_random_uuid(), 'OTRAS HEPATITIS VIRALES AGUDAS'),
  (gen_random_uuid(), 'HEPATITIS AGUDA TIPO C'),
  (gen_random_uuid(), 'HEPATITIS AGUDA TIPO E'),
  (gen_random_uuid(), 'HEPATITIS VIRAL CRONICA'),
  (gen_random_uuid(), 'HEPATITIS VIRAL SIN OTRA ESPECIFICACION'),
  (gen_random_uuid(), 'SECUELAS DE HEPATITIS VIRAL'),
  (gen_random_uuid(), 'HEPATITIS ALCOHOLICA'),
  (gen_random_uuid(), 'ENFERMEDAD TOXICA DEL HIGADO CON HEPATITIS AGUDA'),
  (gen_random_uuid(), 'ENFERMEDAD TOXICA DEL HIGADO CON HEPATITIS CRONICA PERSISTENTE'),
  (gen_random_uuid(), 'HEPATITIS CRONICA NO CLASIFICADA EN OTRA PARTE'),
  (gen_random_uuid(), 'HEPATITIS REACTIVA NO ESPECIFICA'),
  (gen_random_uuid(), 'HEPATITIS VIRAL QUE COMPLICA EL EMBARAZO EL PARTO Y EL PUERPERIO'),
  (gen_random_uuid(), 'HEPATITIS VIRAL CONGENITA'),
  (gen_random_uuid(), 'CONTACTO CON Y EXPOSICION A HEPATITIS VIRAL'),
  (gen_random_uuid(), 'PORTADOR DE HEPATITIS VIRAL'),
  (gen_random_uuid(), 'NECESIDAD DE INMUNIZACION CONTRA LA HEPATITIS VIRAL'),
  (gen_random_uuid(), 'INFECCION ANOGENITAL DEBIDA A VIRUS DEL HERPES [HERPES SIMPLE]'),
  (gen_random_uuid(), 'INFECCIONES HERPETICAS [HERPES SIMPLE]'),
  (gen_random_uuid(), 'HERPES ZOSTER'),
  (gen_random_uuid(), 'HERPES ZOSTER CON OTRAS COMPLICACIONES'),
  (gen_random_uuid(), 'HERPES ZOSTER SIN COMPLICACIONES'),
  (gen_random_uuid(), 'MONONUCLEOSIS DEBIDA A HERPES VIRUS GAMMA'),
  (gen_random_uuid(), 'NEURALGIA POSTHERPES ZOSTER (B02.2+)'),
  (gen_random_uuid(), 'QUERATITIS Y QUERATOCONJUNTIVITIS POR HERPES SIMPLE (B00.5+)'),
  (gen_random_uuid(), 'HERPES GESTACIONAL'),
  (gen_random_uuid(), 'INFECCIONES CONGENITAS POR VIRUS DEL HERPES SIMPLE'),
  (gen_random_uuid(), 'HIPERTENSION ESENCIAL (PRIMARIA)'),
  (gen_random_uuid(), 'HIPERTENSION SECUNDARIA'),
  (gen_random_uuid(), 'HIPERTENSION PULMONAR PRIMARIA'),
  (gen_random_uuid(), 'HIPERTENSION PORTAL'),
  (gen_random_uuid(), 'HIPERTENSION PREEXISTENTE QUE COMPLICA EL EMBARAZO EL PARTO Y EL PUERPERIO'),
  (gen_random_uuid(), 'HIPERTENSION MATERNA NO ESPECIFICADA'),
  (gen_random_uuid(), 'HIPERTENSION NEONATAL'),
  (gen_random_uuid(), 'LECTURA ELEVADA DE LA PRESION SANGUINEA SIN DIAGNOSTICO DE HIPERTENSION'),
  (gen_random_uuid(), 'TIROTOXICOSIS [HIPERTIROIDISMO]'),
  (gen_random_uuid(), 'HIPERTIROIDISMO NEONATAL TRANSITORIO'),
  (gen_random_uuid(), 'HIPOTIROIDISMO SUBCLINICO POR DEFICIENCIA DE YODO'),
  (gen_random_uuid(), 'OTRO HIPOTIROIDISMO'),
  (gen_random_uuid(), 'RENAL CRONICA/AGUDA'),
  (gen_random_uuid(), 'INSUFICIENCIA RENAL AGUDA'),
  (gen_random_uuid(), 'INSUFICIENCIA RENAL CRONICA'),
  (gen_random_uuid(), 'INSUFICIENCIA RENAL NO ESPECIFICADA'),
  (gen_random_uuid(), 'INSUFICIENCIA RENAL CONSECUTIVA AL ABORTO AL EMBARAZO ECTOPICO Y AL EMBARA'),
  (gen_random_uuid(), 'INSUFICIENCIA RENAL AGUDA POSTPARTO'),
  (gen_random_uuid(), 'INSUFICIENCIA RENAL CONGENITA'),
  (gen_random_uuid(), 'LINFOMA DE CELULAS T PERIFERICO Y CUTANEO'),
  (gen_random_uuid(), 'PAPULOSIS LINFOMATOIDE'),
  (gen_random_uuid(), 'VERTIGO PAROXISTICO BENIGNO'),
  (gen_random_uuid(), 'MELANOMA MALIGNO DE LA PIEL'),
  (gen_random_uuid(), 'MELANOMA IN SITU'),
  (gen_random_uuid(), 'MIELOMA MULTIPLE'),
  (gen_random_uuid(), 'OSTEOPOROSIS EN MIELOMATOSIS MULTIPLE (C90.0+)'),
  (gen_random_uuid(), 'MONONUCLEOSIS INFECCIOSA'),
  (gen_random_uuid(), 'MONONUCLEOSIS POR CITOMEGALOVIRUS'),
  (gen_random_uuid(), 'PAROTIDITIS INFECCIOSA'),
  (gen_random_uuid(), 'PAROTIDITIS INFECCIOSA CON OTRAS COMPLICACIONES'),
  (gen_random_uuid(), 'PAROTIDITIS SIN COMPLICACIONES'),
  (gen_random_uuid(), 'NECESIDAD DE INMUNIZACION SOLO CONTRA LA PAROTIDITIS'),
  (gen_random_uuid(), 'OTROS TRASTORNOS ARTICULARES NO CLASIFICADOS EN OTRA PARTE'),
  (gen_random_uuid(), 'CONTRACTURA ARTICULAR'),
  (gen_random_uuid(), 'OTRAS INESTABILIDADES ARTICULARES'),
  (gen_random_uuid(), 'TRASTORNO ARTICULAR NO ESPECIFICADO'),
  (gen_random_uuid(), 'SARCOMA DE KAPOSI'),
  (gen_random_uuid(), 'LINFOSARCOMA'),
  (gen_random_uuid(), 'SARCOMA MIELOIDE'),
  (gen_random_uuid(), 'SINUSITIS AGUDA'),
  (gen_random_uuid(), 'SINUSITIS CRONICA'),
  (gen_random_uuid(), 'AFASIA ADQUIRIDA CON EPILEPSIA [LANDAU-KLEFFNER]'),
  (gen_random_uuid(), 'HISTORIA FAMILIAR DE EPILEPSIA Y OTRAS ENFERMEDADES DEL SISTEMA NERVIOSO'),
  (gen_random_uuid(), 'INSUFICIENCIA CARDIACA'),
  (gen_random_uuid(), 'INSUFICIENCIA CARDIACA NEONATAL'),
  (gen_random_uuid(), 'AGUDA'),
  (gen_random_uuid(), 'RINOFARINGITIS CRONICA'),
  (gen_random_uuid(), 'AMIGDALITIS AGUDA'),
  (gen_random_uuid(), 'AMIGDALITIS CRONICA'),
  (gen_random_uuid(), 'SINDROME DE DIFICULTAD RESPIRATORIA DEL ADULTO'),
  (gen_random_uuid(), 'INSUFICIENCIA RESPIRATORIA NO CLASIFICADA EN OTRA PARTE'),
  (gen_random_uuid(), 'CUERPO EXTRANIO EN LAS VIAS RESPIRATORIAS'),
  (gen_random_uuid(), 'RINITIS ALERGICA Y VASOMOTORA'),
  (gen_random_uuid(), 'RINITIS / RINOFARINGITIS Y FARINGITIS CRONICAS'),
  (gen_random_uuid(), 'RINITIS CRONICA'),
  (gen_random_uuid(), 'ASMA PREDOMINANTEMENTE ALERGICA'),
  (gen_random_uuid(), 'ASMA NO ALERGICA'),
  (gen_random_uuid(), 'ULCERA GASTRICA'),
  (gen_random_uuid(), 'ULCERA DUODENAL'),
  (gen_random_uuid(), 'ULCERA PEPTICA DE SITIO NO ESPECIFICADO'),
  (gen_random_uuid(), 'ULCERA GASTROYEYUNAL'),
  (gen_random_uuid(), 'GASTRITIS Y DUODENITIS'),
  (gen_random_uuid(), 'OTRAS GASTRITIS AGUDAS'),
  (gen_random_uuid(), 'GASTRITIS CRONICA NO ESPECIFICADA'),
  (gen_random_uuid(), 'APENDICITIS AGUDA'),
  (gen_random_uuid(), 'APENDICITIS AGUDA CON PERITONITIS GENERALIZADA'),
  (gen_random_uuid(), 'CIRROSIS HEPATICA ALCOHOLICA'),
  (gen_random_uuid(), 'FIBROSIS Y CIRROSIS DEL HIGADO'),
  (gen_random_uuid(), 'PARAPSORIASIS SIN ESPECIFICAR'),
  (gen_random_uuid(), 'ARTRITIS JUVENIL EN LA PSORIASIS (L40.5+)'),
  (gen_random_uuid(), 'ALOPECIA AREATA'),
  (gen_random_uuid(), 'ALOPECIA CONGENITA'),
  (gen_random_uuid(), 'LUPUS ERITEMATOSO SISTEMICO'),
  (gen_random_uuid(), 'COLICO RENAL NO ESPECIFICADO'),
  (gen_random_uuid(), 'PREECLAMPSIA NO ESPECIFICADA'),
  (gen_random_uuid(), 'ALERGICA'),
  (gen_random_uuid(), 'ALERGIA NO ESPECIFICADA'),
  (gen_random_uuid(), 'HISTORIA PERSONAL DE ALERGIA A DROGAS MEDICAMENTOS Y SUSTANCIAS BIOLOGICAS'),
  (gen_random_uuid(), 'HISTORIA PERSONAL DE ALERGIA NO DEBIDA A DROGAS NI A SUSTANCIAS BIOLOGICAS'),
  (gen_random_uuid(), 'OTROS SINDROMES DE CEFALEA'),
  (gen_random_uuid(), 'TRASTORNO DEL ALMACENAMIENTO DE LIPIDOS NO ESPECIFICADO'),
  (gen_random_uuid(), 'HIPERCOLESTEROLEMIA PURA'),
  (gen_random_uuid(), 'MENSTRUACION AUSENTE ESCASA O RARA'),
  (gen_random_uuid(), 'MENSTRUACION IRREGULAR NO ESPECIFICADA'),
  (gen_random_uuid(), 'ESTADOS ASOCIADOS CON MENOPAUSIA ARTIFICIAL'),
  (gen_random_uuid(), 'AMENORREA SIN OTRA ESPECIFICACION'),
  (gen_random_uuid(), 'MAREO Y DESVANECIMIENTO'),
  (gen_random_uuid(), 'ANTIGONADOTROFINAS ANTIESTROGENOS Y ANTIANDROGENOS NO CLASIFICADOS EN OTR'),
  (gen_random_uuid(), 'DOLOR ABDOMINAL Y PELVICO'),
  (gen_random_uuid(), 'TRASTORNOS SUDORIPAROS ECRINOS'),
  (gen_random_uuid(), 'TRASTORNOS SUDORIPAROS APOCRINOS'),
  (gen_random_uuid(), 'OTROS PROCEDIMIENTOS QUIRURGICOS'),
  (gen_random_uuid(), 'INFECCION DE VIAS URINARIAS SITIO NO ESPECIFICADO'),
  (gen_random_uuid(), 'INFECCION DE LAS VIAS GENITOURINARIAS EN EL EMBARAZO'),
  (gen_random_uuid(), 'SINDROME DE RAYNAUD'),
  (gen_random_uuid(), 'IMPOTENCIA DE ORIGEN ORGANICO'),
  (gen_random_uuid(), 'MEGACOLON NO CLASIFICADO EN OTRA PARTE'),
  (gen_random_uuid(), 'MEGACOLON EN LA ENFERMEDAD DE CHAGAS (B57.3+)'),
  (gen_random_uuid(), 'TRASTORNO DEL HUESO NO ESPECIFICADO'),
  (gen_random_uuid(), 'LUMBAGO NO ESPECIFICADO'),
  (gen_random_uuid(), 'LUMBAGO CON CIATICA'),
  (gen_random_uuid(), 'OTRAS ENFERMEDADES CEREBROVASCULARES'),
  (gen_random_uuid(), 'ANGINA DE PECHO'),
  (gen_random_uuid(), 'ANGINA DE PECHO CON ESPASMO DOCUMENTADO'),
  (gen_random_uuid(), 'BOCIO DIFUSO (ENDEMICO) RELACIONADO CON DEFICIENCIA DE YODO'),
  (gen_random_uuid(), 'BOCIO MULTINODULAR (ENDEMICO) RELACIONADO CON DEFICIENCIA DE YODO'),
  (gen_random_uuid(), 'HIPOTIROIDISMO CONGENITO CON BOCIO DIFUSO'),
  (gen_random_uuid(), 'OTRO BOCIO NO TOXICO'),
  (gen_random_uuid(), 'BOCIO NEONATAL NO CLASIFICADO EN OTRA PARTE'),
  (gen_random_uuid(), 'EXAMEN DE SEGUIMIENTO CONSECUTIVO AL TRATAMIENTO POR TUMOR MALIGNO'),
  (gen_random_uuid(), 'DERMATITIS ATOPICA'),
  (gen_random_uuid(), 'DERMATITIS ALERGICA DE CONTACTO'),
  (gen_random_uuid(), 'DERMATITIS DE CONTACTO POR IRRITANTES'),
  (gen_random_uuid(), 'DERMATITIS EXFOLIATIVA'),
  (gen_random_uuid(), 'OTRAS DERMATITIS'),
  (gen_random_uuid(), 'HEPATOMEGALIA NO CLASIFICADA EN OTRA PARTE'),
  (gen_random_uuid(), 'HEPATOMEGALIA Y ESPLENOMEGALIA NO CLASIFICADAS EN OTRA PARTE'),
  (gen_random_uuid(), 'OTRAS ENFERMEDADES INFLAMATORIAS DEL HIGADO'),
  (gen_random_uuid(), 'OTRAS ENFERMEDADES DEL HIGADO'),
  (gen_random_uuid(), 'OTRAS INTOXICACIONES ALIMENTARIAS BACTERIANAS'),
  (gen_random_uuid(), 'EVIDENCIA DE ALCOHOLISMO DETERMINADA POR EL NIVEL DE INTOXICACION'),
  (gen_random_uuid(), 'MENSTRUACION EXCESIVA FRECUENTE E IRREGULAR'),
  (gen_random_uuid(), 'OTROS TRASTORNOS DEL DESARROLLO Y CRECIMIENTO OSEO'),
  (gen_random_uuid(), 'OSTEOPOROSIS CON FRACTURA PATOLOGICA'),
  (gen_random_uuid(), 'OSTEOPOROSIS SIN FRACTURA PATOLOGICA'),
  (gen_random_uuid(), 'OSTEOPOROSIS EN ENFERMEDADES CLASIFICADAS EN OTRA PARTE'),
  (gen_random_uuid(), 'PIELONEFRITIS CRONICA NO OBSTRUCTIVA ASOCIADA CON REFLUJO'),
  (gen_random_uuid(), 'PIELONEFRITIS CRONICA OBSTRUCTIVA'),
  (gen_random_uuid(), 'ENFERMEDADES INFLAMATORIAS DE LA PROSTATA'),
  (gen_random_uuid(), 'OTROS TRASTORNOS DE LA PROSTATA'),
  (gen_random_uuid(), 'HIPERPLASIA DE LA PROSTATA'),
  (gen_random_uuid(), 'NAUSEA Y VOMITO'),
  (gen_random_uuid(), 'ABORTO ESPONTANEO'),
  (gen_random_uuid(), 'INFERTILIDAD FEMENINA ASOCIADA CON FALTA DE OVULACION'),
  (gen_random_uuid(), 'ANGINA INESTABLE'),
  (gen_random_uuid(), 'OTROS TRASTORNOS ARTICULARES ESPECIFICOS'),
  (gen_random_uuid(), 'PERDIDA ANORMAL DE PESO'),
  (gen_random_uuid(), 'BAJO PESO PARA LA EDAD GESTACIONAL'),
  (gen_random_uuid(), 'OTRO PESO BAJO AL NACER'),
  (gen_random_uuid(), 'CONJUNTIVITIS CRONICA'),
  (gen_random_uuid(), 'CONJUNTIVITIS VIRAL'),
  (gen_random_uuid(), 'OTRAS CONJUNTIVITIS AGUDAS'),
  (gen_random_uuid(), 'PRESENCIA DE IMPLANTES E INJERTOS CARDIOVASCULARES'),
  (gen_random_uuid(), 'DESNUTRICION PROTEICOCALORICA SEVERA NO ESPECIFICADA'),
  (gen_random_uuid(), 'DESNUTRICION EN EL EMBARAZO'),
  (gen_random_uuid(), 'RETARDO DEL CRECIMIENTO FETAL Y DESNUTRICION FETAL'),
  (gen_random_uuid(), 'PRESENCIA DE ALCOHOL EN LA SANGRE NIVEL NO ESPECIFICADO'),
  (gen_random_uuid(), 'ALCOHOLISMO NIVEL DE INTOXICACION NO ESPECIFICADO'),
  (gen_random_uuid(), 'EDEMA NO CLASIFICADO EN OTRA PARTE'),
  (gen_random_uuid(), 'EDEMA LOCALIZADO'),
  (gen_random_uuid(), 'EDEMA GENERALIZADO'),
  (gen_random_uuid(), 'ENFERMEDAD DE TRANSMISION SEXUAL NO ESPECIFICADA'),
  (gen_random_uuid(), 'OTROS TRASTORNOS RESPIRATORIOS'),
  (gen_random_uuid(), 'HEMORRAGIA Y HEMATOMA QUE COMPLICAN UN PROCEDIMIENTO NO CLASIFICADOS EN OT'),
  (gen_random_uuid(), 'ICTERICIA NO ESPECIFICADA'),
  (gen_random_uuid(), 'ICTERICIA NEONATAL DEBIDA A OTRAS HEMOLISIS EXCESIVAS'),
  (gen_random_uuid(), 'ICTERICIA NEONATAL POR OTRAS CAUSAS Y POR LAS NO ESPECIFICADAS'),
  (gen_random_uuid(), 'LEUCEMIA NO ESPECIFICADA'),
  (gen_random_uuid(), 'LEUCEMIA LINFOIDE'),
  (gen_random_uuid(), 'LEUCEMIA MIELOIDE'),
  (gen_random_uuid(), 'LEUCEMIA MONOCITICA'),
  (gen_random_uuid(), 'LINFOMA HISTIOCITICO VERDADERO'),
  (gen_random_uuid(), 'LINFOMA NO HODGKIN NO ESPECIFICADO'),
  (gen_random_uuid(), 'OTROS TRASTORNOS METABOLICOS'),
  (gen_random_uuid(), 'NEUMONIA NO ESPECIFICADA'),
  (gen_random_uuid(), 'DOLOR PRECORDIAL'),
  (gen_random_uuid(), 'SINDROMES VERTIGINOSOS EN ENFERMEDADES CLASIFICADAS EN OTRA PARTE'),
  (gen_random_uuid(), 'VERTIGO EPIDEMICO'),
  (gen_random_uuid(), 'VERTIGO DE ORIGEN CENTRAL'),
  (gen_random_uuid(), 'TOS FERINA NO ESPECIFICADA'),
  (gen_random_uuid(), 'SINDROME DE OVARIO POLIQUISTICO'),
  (gen_random_uuid(), 'OVARIO POLIQUISTICO C/HIRSUTISMO'),
  (gen_random_uuid(), 'SUPERVISION DE EMBARAZO NORMAL')
ON CONFLICT ("nombre") DO NOTHING;
