-- Script para insertar el catálogo completo de Patologías Predefinidas
-- Este script es IDEMPOTENTE: puede ejecutarse en Supabase y no sobrescribirá si ya existen.

INSERT INTO "Patologia" ("id", "nombre") VALUES
('uuid-1', 'Abdomen Agudo'),
('uuid-2', 'Abortos Espontáneos'),
('uuid-3', 'Acné'),
('uuid-4', 'ACV Isquémico'),
('uuid-5', 'Adenomegalia'),
('uuid-6', 'Alopecia'),
('uuid-7', 'Alergia Respiratoria'),
('uuid-8', 'Amigdalitis'),
('uuid-9', 'Amenorrea'),
('uuid-10', 'Amenorrea Primaria'),
('uuid-11', 'Amenorrea Secundaria'),
('uuid-12', 'Anaovulación'),
('uuid-13', 'Anemia'),
('uuid-14', 'Aneurisma'),
('uuid-15', 'Angina'),
('uuid-16', 'Angor'),
('uuid-17', 'Anorexia'),
('uuid-18', 'Apendicitis'),
('uuid-19', 'Arritmia'),
('uuid-20', 'Arritmias'),
('uuid-21', 'Artralgia'),
('uuid-22', 'Artritis Reumatoidea'),
('uuid-23', 'Artrosis'),
('uuid-24', 'Asma'),
('uuid-25', 'Astenia'),
('uuid-26', 'Bajo Peso'),
('uuid-27', 'Bocio'),
('uuid-28', 'Bronquitis Obstructiva'),
('uuid-29', 'Cefalea'),
('uuid-30', 'Cirrosis'),
('uuid-31', 'Climaterio'),
('uuid-32', 'Colelitiasis'),
('uuid-33', 'Cólico Renal'),
('uuid-34', 'Conjuntivitis'),
('uuid-35', 'Constipación'),
('uuid-36', 'Control By Pass'),
('uuid-37', 'Control de Ca.'),
('uuid-38', 'Dermatitis'),
('uuid-39', 'Desnutrición'),
('uuid-40', 'Diabetes Mellitus'),
('uuid-41', 'Diarrea'),
('uuid-42', 'Dislipemia'),
('uuid-43', 'Disnea'),
('uuid-44', 'Dispepsia'),
('uuid-45', 'Disuria'),
('uuid-46', 'Dolor Abdominal'),
('uuid-47', 'Eclampsia'),
('uuid-48', 'Edemas'),
('uuid-49', 'Embarazo - Control 1er. Trimestre'),
('uuid-50', 'Embarazo - Control 2do. Trimestre'),
('uuid-51', 'Embarazo - Control 3er. Trimestre'),
('uuid-52', 'Enfermedad de Hodgkin'),
('uuid-53', 'Enfermedad de Transmisión Sexual'),
('uuid-54', 'Epistaxis'),
('uuid-55', 'Epilepsia'),
('uuid-56', 'EPOC - Insuficiencia Respiratoria'),
('uuid-57', 'Escabiosis'),
('uuid-58', 'Etilismo'),
('uuid-59', 'Faringitis'),
('uuid-60', 'Fibrosis Quística'),
('uuid-61', 'Fiebre'),
('uuid-62', 'Fiebre Reumática'),
('uuid-63', 'Gastroenteritis'),
('uuid-64', 'Gota'),
('uuid-65', 'Hematomas'),
('uuid-66', 'Hematuria'),
('uuid-67', 'Hepatitis'),
('uuid-68', 'Hepatomegalia'),
('uuid-69', 'Hepatopatía'),
('uuid-70', 'Herpes'),
('uuid-71', 'Hipercolesterolemia / Colesterolemia'),
('uuid-72', 'Hipertensión Arterial'),
('uuid-73', 'Hipertiroidismo'),
('uuid-74', 'Hipogonadismo Masculino'),
('uuid-75', 'Hipotiroidismo'),
('uuid-76', 'Hirsutismo'),
('uuid-77', 'Ictericia'),
('uuid-78', 'Infección Urinaria'),
('uuid-79', 'Infertilidad Femenina'),
('uuid-80', 'Infertilidad Masculina'),
('uuid-81', 'Insuficiencia Cardíaca'),
('uuid-82', 'Insuficiencia Renal Crónica/Aguda'),
('uuid-83', 'Intoxicación'),
('uuid-84', 'Leucemia'),
('uuid-85', 'Linfoma'),
('uuid-86', 'Linfoma No-Hodgkin'),
('uuid-87', 'Lipotimia'),
('uuid-88', 'Litiasis Vesicular'),
('uuid-89', 'Lumbalgia'),
('uuid-90', 'Lupus Eritematoso'),
('uuid-91', 'Mareos'),
('uuid-92', 'Melanoma'),
('uuid-93', 'Menopausia'),
('uuid-94', 'Metrorragia'),
('uuid-95', 'Metabolopatía'),
('uuid-96', 'Mialgia'),
('uuid-97', 'Mieloma'),
('uuid-98', 'Mononucleosis y la Infecciosa'),
('uuid-99', 'Megacolon'),
('uuid-100', 'Neumopatía'),
('uuid-101', 'Obesidad'),
('uuid-102', 'Osteopenia'),
('uuid-103', 'Osteoporosis'),
('uuid-104', 'Parotiditis'),
('uuid-105', 'Pielonefritis'),
('uuid-106', 'Poliartralgias'),
('uuid-107', 'Polidipsia'),
('uuid-108', 'Precordialgia - Dolor Precordial'),
('uuid-109', 'Prequirúrgico'),
('uuid-110', 'Prostatismo'),
('uuid-111', 'Prurito'),
('uuid-112', 'Psoriasis'),
('uuid-113', 'Raynaud, Enfermedad - Síndrome'),
('uuid-114', 'Reacción Alérgica'),
('uuid-115', 'Rinitis'),
('uuid-116', 'Rinofaringitis Aguda'),
('uuid-117', 'Sarcoma'),
('uuid-118', 'Síndrome de la Silla Turca'),
('uuid-119', 'Síndrome de Ovario Poliquístico (SOPQ)'),
('uuid-120', 'Síndrome Febril Prolongado'),
('uuid-121', 'Síndrome Vertiginoso'),
('uuid-122', 'Sinusitis'),
('uuid-123', 'Sobrepeso'),
('uuid-124', 'Sudoración'),
('uuid-125', 'Tos Crónica'),
('uuid-126', 'Úlcera Gástrica / Duodenal'),
('uuid-127', 'Urticaria'),
('uuid-128', 'Vómitos'),
('uuid-129', 'Otros')
ON CONFLICT ("nombre") DO NOTHING;
