-- Catálogo de Medicamentos Predefinidos (principio activo · concentración · presentación).
-- IDEMPOTENTE: re-ejecutable en Supabase sin duplicar (ON CONFLICT por la clave compuesta).
-- Requiere haber corrido antes migrate_db_medicamentos_v2.sql (columnas + índice único compuesto).

INSERT INTO "MedicamentoPredefinido" ("id", "nombre", "concentracion", "presentacion") VALUES
  (gen_random_uuid(), 'ACETAMINOFEN', '500 MG', 'TABLETAS'),
  (gen_random_uuid(), 'ACETAMINOFEN', '180 MG / 5 ML', 'JARABE'),
  (gen_random_uuid(), 'ACETAMINOFEN / CAFEINA', '500 / 40 MG', 'TABLETA'),
  (gen_random_uuid(), 'ACICLOVIR', '200 MG', 'TABLETA'),
  (gen_random_uuid(), 'ACICLOVIR', '400 MG', 'TABLETA'),
  (gen_random_uuid(), 'ACICLOVIR', '0.05', 'CREMA'),
  (gen_random_uuid(), 'ACIDO ACETILSALICILICO', '81 MG', 'TABLETA'),
  (gen_random_uuid(), 'ACIDO ACETILSALICILICO', '100 MG', 'TABLETA'),
  (gen_random_uuid(), 'ACIDO ASCORBICO', '5 MG', 'TABLETA'),
  (gen_random_uuid(), 'ACIDO ASCORBICO', '120 ML', 'JARABE'),
  (gen_random_uuid(), 'ACIDO FOLICO', '10 MG', 'TABLETA'),
  (gen_random_uuid(), 'ACIDO FOLICO', '5 MG', 'TABLETA'),
  (gen_random_uuid(), 'ACIDO VALPROICO', '500 MG', 'TABLETAS'),
  (gen_random_uuid(), 'ACIDO VALPROICO', '250 MG / 5ML', 'JARABE'),
  (gen_random_uuid(), 'AMBROXOL', '30 MG / 5 ML', 'JARABE'),
  (gen_random_uuid(), 'AMBROXOL', '15 MG / 5 ML', 'JARABE'),
  (gen_random_uuid(), 'AMLODIPINA', '5 MG', 'TABLETA'),
  (gen_random_uuid(), 'AMLODIPINA', '10 MG', 'TABLETA'),
  (gen_random_uuid(), 'AMOXICILINA', '500 MG', 'TABLETA'),
  (gen_random_uuid(), 'AMOXICILINA', '600 MG / 5 ML', 'SUSPENSIÓN'),
  (gen_random_uuid(), 'AMOXICILINA / ACIDO CLAVULANICO', '850 MG', 'TABLETA'),
  (gen_random_uuid(), 'AMOXICILINA / ACIDO CLAVULANICO', '500 MG', 'TABLETA'),
  (gen_random_uuid(), 'AMOXICILINA / ACIDO CLAVULANICO', '400 / 5 ML', 'SUSPENSION'),
  (gen_random_uuid(), 'AMPICILINA', '500', 'TABLETA'),
  (gen_random_uuid(), 'ARTRODAR', '50 MG', 'CAPSULAS'),
  (gen_random_uuid(), 'ARTROVIT', '', 'CAPSULAS'),
  (gen_random_uuid(), 'ATENOLOL', '100 MG', 'TABLETA'),
  (gen_random_uuid(), 'ATENOLOL', '25 MG', 'TABLETA'),
  (gen_random_uuid(), 'ATENOLOL', '50 MG', 'TABLETA'),
  (gen_random_uuid(), 'ATORVASTATINA', '40 MG', 'TABLETA'),
  (gen_random_uuid(), 'ATORVASTATINA', '20 MG', 'TABLETA'),
  (gen_random_uuid(), 'AZITROMICINA', '500 MG', 'TABLETA'),
  (gen_random_uuid(), 'AZITROMICINA', '200 MG / 5ML', 'SUSPENSIÓN'),
  (gen_random_uuid(), 'BACITRACINA', '500 / 20UI', 'UNGÜENTO'),
  (gen_random_uuid(), 'BENCIDAMINA', '0,15 / 180 ML', 'JARABE'),
  (gen_random_uuid(), 'BETAHISTINA', '16 MG', 'TABLETA'),
  (gen_random_uuid(), 'BETAMETASONA', '4 ML', 'AMPOLLA'),
  (gen_random_uuid(), 'BETAMETASONA / CLOTRIMAZOL / NEOMICINA', '', 'CREMA'),
  (gen_random_uuid(), 'BIPERIDENO', '2 MG', 'TABLETA'),
  (gen_random_uuid(), 'BISACODILO', '5 MG', 'TABLETA'),
  (gen_random_uuid(), 'BISOPROLOL', '2,5 MG', 'TABLETA'),
  (gen_random_uuid(), 'BISOPROLOL', '50 MG', 'TABLETA'),
  (gen_random_uuid(), 'BISPROLOL', '10 MG', 'TABLETA'),
  (gen_random_uuid(), 'BROMURO DE IPRATROPIO', '0.0025', 'GOTAS NEBULIZAR'),
  (gen_random_uuid(), 'BROMURO DE IPRATROPIO', '20 MCG', 'INHALADOR'),
  (gen_random_uuid(), 'BUDESONIDA', '200 MCG', 'INHALADOR'),
  (gen_random_uuid(), 'BUDESONIDA', '', 'GOTAS NEBULIZAR'),
  (gen_random_uuid(), 'BUDESONIDA / FORMOTEROL', '160 / 4,5', 'INHALADOR'),
  (gen_random_uuid(), 'CALCIO / VITAMINA D', '600 MG / 400 MG', 'TABLETA'),
  (gen_random_uuid(), 'CANDESARTAN', '8 MG', 'TABLETA'),
  (gen_random_uuid(), 'CANDESARTAN', '16 MG', 'TABLETA'),
  (gen_random_uuid(), 'CARBAMAZEPINA', '200 MG', 'TABLETA'),
  (gen_random_uuid(), 'CARBONATO DE CALCIO', '1500 MG', 'CAPSULAS'),
  (gen_random_uuid(), 'CARVEDILOL', '12,5 MG', 'TABLETA'),
  (gen_random_uuid(), 'CARVEDILOL', '6,25 MG', 'TABLETA'),
  (gen_random_uuid(), 'CEFADROXLLO', '250 MG / 5 ML', 'SUSPENSION'),
  (gen_random_uuid(), 'CEFIXIMA', '100 MG / 5 ML', 'SUSPENSIÓN'),
  (gen_random_uuid(), 'CEFRADOXILO', '500 MG', 'TABLETA'),
  (gen_random_uuid(), 'CETIRICINA', '5 MG / 5ML', 'JARABE'),
  (gen_random_uuid(), 'CETIRIZINA', '10 MG', 'TABLETA'),
  (gen_random_uuid(), 'CETIRIZINA', '5 MG', 'TABLETA'),
  (gen_random_uuid(), 'CIPROFLOXACINA', '500 MG', 'TABLETA'),
  (gen_random_uuid(), 'CIPROFLOXACINA', '0.003', 'SOLUCION OTICA'),
  (gen_random_uuid(), 'CITICOLINA', '500 MG', 'TABLETA'),
  (gen_random_uuid(), 'CITRATO DE CALCIO', '', 'TABLETA'),
  (gen_random_uuid(), 'CLARIDEX', '', 'SOLUCION OFTAMILCA'),
  (gen_random_uuid(), 'CLINDAMICINA', '300 MG', 'TABLETA'),
  (gen_random_uuid(), 'CLOPIDOGREL', '75 MG', 'TABLETA'),
  (gen_random_uuid(), 'CLORHIDRATO DE MEMANTINA', '10 MG', 'TABLETAS'),
  (gen_random_uuid(), 'CLOTRIMAZOL', '100 MG', 'OVULOS'),
  (gen_random_uuid(), 'CLOTRIMAZOL', '0.01', 'CREMA'),
  (gen_random_uuid(), 'COLYPAN (TRIMEBUTINA)', '200 MG', 'TABLETA'),
  (gen_random_uuid(), 'COMPLEJO B', '10 ML', 'INYECTABLE'),
  (gen_random_uuid(), 'COMPLEJO B12', '3 ML', 'INYECTABLE'),
  (gen_random_uuid(), 'DECUALINO / LIDOCAINA', '0,5 / 5 MG', 'TABLETA'),
  (gen_random_uuid(), 'DEFLAZACORT', '6 MG', 'TABLETA'),
  (gen_random_uuid(), 'DEFLAZACORT', '30 MG', 'TABLETA'),
  (gen_random_uuid(), 'DESLORATADINA', '5 MG', 'TABLETA'),
  (gen_random_uuid(), 'DESLORATADINA', '2,5 MG / 5 ML', 'JARABE'),
  (gen_random_uuid(), 'DEXAMETASONA', '4 MG', 'TABLETA'),
  (gen_random_uuid(), 'DEXAMETASONA FOSFATO', '4 MG / ML', 'INYECTABLE'),
  (gen_random_uuid(), 'DEXAMETAZONA', '8 MG / 2 ML', 'INYECTABLE'),
  (gen_random_uuid(), 'DEXTRAN', '15 ML', 'LAGRIMAS ARTIFICIALES'),
  (gen_random_uuid(), 'DEXTROMETORFANO', '15 MG / 5 ML', 'JARABE'),
  (gen_random_uuid(), 'DICLOFENAC POTASICO', '50 MG', 'TABLETA'),
  (gen_random_uuid(), 'DICLOFENAC POTASICO', '25 MG / 5 ML', 'SUSPENSION'),
  (gen_random_uuid(), 'DICLOFENAC SODICO', '50 MG', 'TABLETA'),
  (gen_random_uuid(), 'DICLOFENAC SODICO', '0.01', 'GEL'),
  (gen_random_uuid(), 'DICLOFENAC SODICO', '75 MG / 3 ML', 'INYECTABLE'),
  (gen_random_uuid(), 'DICLOFENAC SODICO', '100 MG', 'SUPOSITORIO'),
  (gen_random_uuid(), 'DIMENHIDRATO', '50 MG', 'TABLETA'),
  (gen_random_uuid(), 'DIOSMINA', '600 MG', 'TABLETA'),
  (gen_random_uuid(), 'DOMPERIDONA', '10 MG', 'TABLETA'),
  (gen_random_uuid(), 'ENALAPRIL', '10 MG', 'TABLETA'),
  (gen_random_uuid(), 'ENALAPRIL', '20 MG', 'TABLETA'),
  (gen_random_uuid(), 'ESCITALOPRAM', '10 MG', 'TABLETAS'),
  (gen_random_uuid(), 'ESOMEPRAZOL', '40 MG', 'CAPSULAS'),
  (gen_random_uuid(), 'ESPIRONOLACTONA', '100 MG', 'TABLETA'),
  (gen_random_uuid(), 'FLUCONAZOL', '150 MG', 'TABLETA'),
  (gen_random_uuid(), 'FUROSEMIDA', '20 MG', 'TABLETA'),
  (gen_random_uuid(), 'FUROSEMIDA', '20 MG / ML', 'INYECTABLE'),
  (gen_random_uuid(), 'GLIMBECLAMIDA', '5 MG', 'TABLETA'),
  (gen_random_uuid(), 'GLIMEPIRIDE', '4 MG', 'TABLETA'),
  (gen_random_uuid(), 'GLIMEPIRIDE', '2 MG', 'TABLETA'),
  (gen_random_uuid(), 'GLUCOSAMINA / CONDROITINA', '250 / 250', 'CAPSULAS'),
  (gen_random_uuid(), 'GLUCOSAMINA / CONDROITINA', '500 / 400 MG', 'TABLETA'),
  (gen_random_uuid(), 'HALOPERIDOL', '50 MG / 1 ML', 'INYECTABLE'),
  (gen_random_uuid(), 'HIDROCLOROTIAZIDA', '12,5 MG', 'TABLETA'),
  (gen_random_uuid(), 'HIERRO', '100 ML', 'AMPOLLAS'),
  (gen_random_uuid(), 'IBUPREFENO', '800 MG', 'TABLETA'),
  (gen_random_uuid(), 'IBUPROFENO', '400 MG', 'TABLETA'),
  (gen_random_uuid(), 'IBUPROFENO', '600 MG', 'TABLETA'),
  (gen_random_uuid(), 'KETOPROFENO', '100 MG', 'TABLETA'),
  (gen_random_uuid(), 'KETOPROFENO', '100 MG / ML', 'INYECTABLE'),
  (gen_random_uuid(), 'KETOROLACO', '30 MG', 'INAYECTABLE'),
  (gen_random_uuid(), 'KETOROLACO TROMETAMINA', '30 MG', 'TABLETA'),
  (gen_random_uuid(), 'LAGRIMAS ARTIFICIALES', '', 'GOTAS'),
  (gen_random_uuid(), 'LEVOFLOXACINA', '750 MG', 'TABLETA'),
  (gen_random_uuid(), 'LEVOFLOXACINA', '500 MG', 'TABLETA'),
  (gen_random_uuid(), 'LEVOSULPIRIDE', '25 MG', 'TABLETA'),
  (gen_random_uuid(), 'LEVOTIROXINA', '50 MG', 'TABLETA'),
  (gen_random_uuid(), 'LEVOTIROXINA', '100 MG', 'TABLETA'),
  (gen_random_uuid(), 'LIDOCAINA', '0.02', 'INYECTABLE'),
  (gen_random_uuid(), 'LOPERAMIDA', '2 MG', 'TABLETA'),
  (gen_random_uuid(), 'LORATADINA', '5 MG', 'TABLETA'),
  (gen_random_uuid(), 'LORATADINA', '10 MG', 'TABLETA'),
  (gen_random_uuid(), 'LORATADINA', '5 MG / ML', 'JARABE'),
  (gen_random_uuid(), 'LOSARTAN POTASICO', '50 MG', 'TABLETA'),
  (gen_random_uuid(), 'LOSARTAN POTASICO', '100 MG', 'TABLETA'),
  (gen_random_uuid(), 'MELOXICAN', '7,5 MG', 'TABLETA'),
  (gen_random_uuid(), 'MELOXICAN', '', 'AMPOLLAS'),
  (gen_random_uuid(), 'METFORMINA', '500 MG', 'TABLETA'),
  (gen_random_uuid(), 'METFORMINA', '850 MG', 'TABLETA'),
  (gen_random_uuid(), 'METFORMINA / SITAGLIPTINA', '50 / 850 MG', 'TABLETAS'),
  (gen_random_uuid(), 'METOCLOPRAMIDA', '100 MG', 'TABLETA'),
  (gen_random_uuid(), 'METOCLOPRAMIDA', '10 MG / 2ML', 'INYECTABLE'),
  (gen_random_uuid(), 'METOCLOPRAMIDA', '5 MG / 5ML', 'JARABE'),
  (gen_random_uuid(), 'METRONIDAZOL', '500', 'OVULOS'),
  (gen_random_uuid(), 'METRONIDAZOL', '250 MG / 5 ML', 'SUSPENSIÓN'),
  (gen_random_uuid(), 'METRONIDAZOL', '500 MG', 'TABLETA'),
  (gen_random_uuid(), 'METRONIDAZOL', '125 MG / 5 ML', 'JARABE'),
  (gen_random_uuid(), 'MONTELUKAST', '10 MG', 'TABLETA'),
  (gen_random_uuid(), 'MULTIVITAMINICO', '', 'TABLETAS'),
  (gen_random_uuid(), 'N-BUTILBROMURO DE HIOSCINA MG', '10 MG', 'INYECTABLE'),
  (gen_random_uuid(), 'NIFEDIPINA', '20 MG', 'TABLETA'),
  (gen_random_uuid(), 'NIFEDIPINA', '10 MG', 'TABLETA'),
  (gen_random_uuid(), 'NIFEDIPINA', '30 MG', 'TABLETA'),
  (gen_random_uuid(), 'NITROFURANTOINA', '100 MG', 'CAPSULAS'),
  (gen_random_uuid(), 'OLMESARTAN', '20 MG', 'TABLETA'),
  (gen_random_uuid(), 'OLMESARTAN', '40 MG', 'TABLETA'),
  (gen_random_uuid(), 'OMEGA 3', '1000 MG', 'CAPSULAS'),
  (gen_random_uuid(), 'OMEPRAZOL', '20 MG', 'TABLETA'),
  (gen_random_uuid(), 'OMEPRAZOL', '40 MG', 'TABLETA'),
  (gen_random_uuid(), 'PANCREATINA', '210 MG', 'TABLETA'),
  (gen_random_uuid(), 'PARACETAMOL', '500 MG', 'TABLETA'),
  (gen_random_uuid(), 'PARACETAMOL', '120 / 5 ML', 'JARABE'),
  (gen_random_uuid(), 'PARACETAMOL / CETIRIZINA / FENILEFRINA', '500 / 5 / 10 MG', 'TABLETA'),
  (gen_random_uuid(), 'PENTOXIFILINA', '40 MG', 'TABLETAS'),
  (gen_random_uuid(), 'POLIOTICO', '', 'GOTAS'),
  (gen_random_uuid(), 'PREDNISOLONA', '0.01', 'SUSPENSIÓN OFTALMICA'),
  (gen_random_uuid(), 'PREDNISONA', '5 MG', 'TABLETA'),
  (gen_random_uuid(), 'PREGABALINA', '75 MG', 'TABLETA'),
  (gen_random_uuid(), 'PREGABALINA / METILCOBALAMINA', '75 / 750', 'TABLETA'),
  (gen_random_uuid(), 'QUETIAPINA', '100 MG', 'TABLETAS'),
  (gen_random_uuid(), 'SALBUTAMOL', 'PUFF', 'INHALADOR'),
  (gen_random_uuid(), 'SALBUTAMOL', '', 'GOTAS NEBULIZAR'),
  (gen_random_uuid(), 'SALES DE REHIDRATACION ORAL', '', 'GRANULADO'),
  (gen_random_uuid(), 'SIMETICONA', '125 MG', 'CAPSULA'),
  (gen_random_uuid(), 'SIMVASTATINA', '20 MG', 'TABLETA'),
  (gen_random_uuid(), 'SIMVASTATINA', '40 MG', 'TABLETAS'),
  (gen_random_uuid(), 'SULFADIAZINA DE PLATA', '0.01', 'CREMA'),
  (gen_random_uuid(), 'SULFATO FERROSO', '300 MG', 'TABLETA'),
  (gen_random_uuid(), 'SULTAMICILINA', '750 MG', 'TABLETA'),
  (gen_random_uuid(), 'TAMSULON', '4 MG', 'TABLETA'),
  (gen_random_uuid(), 'TIMOLOL', '0.005', 'SOLUCION OFTALMICA'),
  (gen_random_uuid(), 'TIOCOLCHICOSIDO', '4 MG', 'TABLETA'),
  (gen_random_uuid(), 'TIOCOLCHICOSIDO', '4 MG / 2 ML', 'INYECTABLE'),
  (gen_random_uuid(), 'TIOCOLCHICOSIDO / IBUPROFENO', '4 / 400 MG', 'TABLETA'),
  (gen_random_uuid(), 'TOBRAMICINA', '0.003', 'SOLUCION OFTALMICA'),
  (gen_random_uuid(), 'TOBRAMICINA / DEXAMETASONA', '03% / 0,1%', 'CREMA'),
  (gen_random_uuid(), 'TRIMETOPRIM / SULFAMETOXAZOL', '16 / 800 MG', 'TABLETA'),
  (gen_random_uuid(), 'TRIMETOPRIM / SULFAMETAXAZOL', '60 ML', 'SUSPENCION'),
  (gen_random_uuid(), 'VALSARTAN', '80 MG', 'TABLETA'),
  (gen_random_uuid(), 'VALSARTAN', '160 MG', 'TABLETA'),
  (gen_random_uuid(), 'VALSARTAN / HTC', '160 / 12,5 MG', 'TABLETA'),
  (gen_random_uuid(), 'VITAMINA D', '1000 UI', ''),
  (gen_random_uuid(), 'VITAMINA E', '1000 UI', ''),
  (gen_random_uuid(), 'WARFARINA', '2.5', 'TABLETA')
ON CONFLICT ("nombre", "concentracion", "presentacion") DO NOTHING;
